name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          args: "--standalone --output=output/doc3.pdf docs/doc3.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
